controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    acker_cont:
      type: ackermann_steering_controller/AckermannSteeringController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

acker_cont:
  ros__parameters:
    publish_rate: 1000.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link
    odom_frame_id: odom
    open_loop: false
    enable_odom_tf: true
    odom_only_twist: false
    use_stamped_vel: false
    velocity_rolling_window_size: 10
    cmd_vel_timeout: 500

    front_steering: true
    front_wheels_names: ['left_chassis_steer_joint', 'right_chassis_steer_joint']
    rear_wheels_names: ['left_drive_wheel_joint', 'right_drive_wheel_joint']
    front_wheel_track: 0.106
    rear_wheel_track: 0.114
    wheelbase: 0.096
    front_wheels_radius: 0.034
    rear_wheels_radius: 0.034
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # Need to be set if fusing odom with other localization source
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # Need to be set if fusing odom with other localization source